apiVersion: skaffold/v3
kind: Config
build:
  tagPolicy:
    inputDigest: {}
  artifacts:
    - image: semiheimer/auth
      context: auth
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: semiheimer/client
      context: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: semiheimer/tickets
      context: tickets
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: semiheimer/orders
      context: orders
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: semiheimer/expiration
      context: expiration
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
      docker:
        dockerfile: Dockerfile
  # local:
  #   push: false
  # googleCloudBuild:
  #   projectId: "ticketing-dev-413111"
manifests:
  rawYaml:
    - ./infra/k8s/*
# deploy:
#   kubectl: {}


